version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: 4

services:
  git-checkout:
    image: bitnami/git:latest
    working_dir: /temp
    command: >
      bash -c " 
        git clone https://github.com/axeleroy/lemmy .git &&
        cd .git &&
        echo 'Copying ./docker/lemmy.hjson ...' &&
        sed -i \"s/ADMIN_USERNAME/$ADMIN_USERNAME/g\" ./docker/lemmy.hjson &&
        sed -i \"s/ADMIN_PASSWORD/$ADMIN_PASSWORD/g\" ./docker/lemmy.hjson &&
        sed -i \"s/POSTGRES_USER/$POSTGRES_USER/g\" ./docker/lemmy.hjson &&
        sed -i \"s/POSTGRES_PWD/$POSTGRES_PWD/g\" ./docker/lemmy.hjson &&
        sed -i \"s/HOSTNAME/$HOSTNAME/g\" ./docker/lemmy.hjson &&
        sed -i \"s/SMTP_SERVER/$SMTP_SERVER/g\" ./docker/lemmy.hjson &&
        sed -i \"s/SMTP_LOGIN/$SMTP_LOGIN/g\" ./docker/lemmy.hjson &&
        sed -i \"s/SMTP_PASSWORD/$SMTP_PASSWORD/g\" ./docker/lemmy.hjson &&
        cp -R ./docker/lemmy.hjson /lemmy-config/config.hjson &&
        echo 'Copying ./docker/nginx.config ...' &&
        cp -R ./docker/nginx.conf /nginx-config &&
        echo 'Copying done!'
      "
    volumes:
      - lemmy-config:/lemmy-config
      - nginx-config:/nginx-config
    environment:
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PWD
      - HOSTNAME
      - SMTP_SERVER
      - SMTP_LOGIN

  proxy:
    image: nginx:1-alpine
    ports:
      # actual and only port facing any connection from outside
      # Note, change the left number if port 1236 is already in use on your system
      # You could use port 80 if you won't use a reverse proxy
      - "1236:1236"
      - "8536:8536"
    volumes:
      - nginx-config:/etc/nginx/
    restart: always
    depends_on:
      - pictrs
      - lemmy-ui
    logging: *default-logging
    networks:
      - lemmy-net
      - bunkerweb-net

  lemmy:
    image: dessalines/lemmy:0.18.0
    # this hostname is used in nginx reverse proxy and also for lemmy ui to connect to the backend, do not change
    hostname: lemmy
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
      - RUST_BACKTRACE=full
    volumes:
      - lemmy-config:/config
    depends_on:
      - postgres
      - pictrs
    logging: *default-logging
    networks:
      - lemmy-net

  lemmy-ui:
    image: dessalines/lemmy-ui:0.18.0
    environment:
      # this needs to match the hostname defined in the lemmy service
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      # set the outside hostname here
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=localhost:1236
      - LEMMY_UI_HTTPS=false
      - LEMMY_UI_DEBUG=true
    depends_on:
      - lemmy
    restart: always
    logging: *default-logging
    init: true
    networks:
      - lemmy-net

  pictrs:
    image: asonix/pictrs:0.4.0-beta.19
    # this needs to match the pictrs url in lemmy.hjson
    hostname: pictrs
    # we can set options to pictrs like this, here we set max. image size and forced format for conversion
    # entrypoint: /sbin/tini -- /usr/local/bin/pict-rs -p /mnt -m 4 --image-format webp
    environment:
      - PICTRS_OPENTELEMETRY_URL=http://otel:4137
      - PICTRS__API_KEY=API_KEY
      - RUST_LOG=debug
      - RUST_BACKTRACE=full
      - PICTRS__MEDIA__VIDEO_CODEC=vp9
      - PICTRS__MEDIA__GIF__MAX_WIDTH=256
      - PICTRS__MEDIA__GIF__MAX_HEIGHT=256
      - PICTRS__MEDIA__GIF__MAX_AREA=65536
      - PICTRS__MEDIA__GIF__MAX_FRAME_COUNT=400
    user: 991:991
    volumes:
      - pictrs:/mnt:Z
    restart: always
    logging: *default-logging
    networks:
      - lemmy-net

  postgres:
    image: postgres:15-alpine
    # this needs to match the database host in lemmy.hjson
    # Tune your settings via
    # https://pgtune.leopard.in.ua/#/
    # You can use this technique to add them here
    # https://stackoverflow.com/a/30850095/1655478
    hostname: postgres
    command:
      [
        "postgres",
        "-c",
        "session_preload_libraries=auto_explain",
        "-c",
        "auto_explain.log_min_duration=5ms",
        "-c",
        "auto_explain.log_analyze=true",
        "-c",
        "track_activity_query_size=1048576",
      ]
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-lemmy}
      - POSTGRES_PASSWORD=${POSTGRES_PWD:-password}
      - POSTGRES_DB=lemmy
    volumes:
      - postgres:/var/lib/postgresql/data:Z
    restart: always
    logging: *default-logging

volumes:
  lemmy-config: {}
  nginx-config: {}
  pictrs: {}
  postgres: {}

networks:
  lemmy-net:
    name: lemmy-net
  bunkerweb-net:
    name: bunkerweb-net
    external: true
